### ISSUE TITLE
Identificación de script con parámetros de la consulta

### ISSUE THREAD

**Issue by jgduenasl** [nestorandrespe/leyes-scraper#1]
Hola @nestorandrespe , estoy tratando de entender en el navegador las acciones que uno ejecuta en la página, y ver en networks cómo se reflejan. Quiero ver cómo se llaman los parámetros y los valores que deja en el código cuando uno hace una acción en la página. Para eso en la opción de `inspect` voy a `network` pero no logro identificar cuál es el script que contiene la información de la consulta.

**Comment by nestorandrespe** [comment]
![image](https://user-images.githubusercontent.com/792228/105790924-29043d00-5f53-11eb-98f9-05c5ed64ed57.png)

se llama _Find_

**Comment by jgduenasl** [comment]
vale listo, ahora lo veo. Todas las api tiene un archivo como este o es una caso particular? cómo identificar dónde es que se pasan los parámetros de consulta cuando no hay api?

**Comment by nestorandrespe** [comment]
Cuando no hay api toca "hackear" un poco el proceso, cargando por un lado la pagina completa como si usaras un navegador y detectatar cada elemento html a través del DOM

**Comment by jgduenasl** [comment]
Vale, gracias.
